export class Compte {
  // tslint:disable-next-line:variable-name
  _id: string;
  nom: string;
  prenom: string;
  nomJF: string;
  email: string;
  // tslint:disable-next-line:variable-name
  code_client: string;
  pays: string;
  adresse: string;
  gouvernorat: string;
  // tslint:disable-next-line:variable-name
  tel_mobile: string;
  // tslint:disable-next-line:variable-name
  tel_domicile: string;
  situation: string;
  // tslint:disable-next-line:variable-name
  date_naissance: Date;
  // tslint:disable-next-line:variable-name
  pays_naissance: string;
  // tslint:disable-next-line:variable-name
  gouvernorat_naissance: string;
  nationalite: string;
  // tslint:disable-next-line:variable-name
  seconde_nationalite: string;
  // tslint:disable-next-line:variable-name
  situation_familiale: string;
  domaine: string;
  profession: string;
  // tslint:disable-next-line:variable-name
  type_compte: string;
  // tslint:disable-next-line:variable-name
  revenu_net_mensuel: string;
  // tslint:disable-next-line:variable-name
  date_creation: Date;
  // tslint:disable-next-line:variable-name
  fin_exercice: string;
  // tslint:disable-next-line:variable-name
  code_activite: string;
  // tslint:disable-next-line:variable-name
  chiffre_affaire: string;
  // tslint:disable-next-line:variable-name
  nbr_salaries: string;
  // tslint:disable-next-line:variable-name
  payes_activite: string;
  // tslint:disable-next-line:variable-name
  type_alimentation: string;
  // tslint:disable-next-line:variable-name
  type_service: string;
  // tslint:disable-next-line:variable-name
  copie_CIN: string;
  // tslint:disable-next-line:variable-name
  fiche_paie: string;
  facture: string;
  etat: boolean;

  constructor() {
  }
}
